name: "Create release"

on:
  push:
    tags:
      - "*"

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Fetch Tags"
        # Workaround for https://github.com/actions/checkout/issues/290
        run: |
          # Avoid git exiting when Actions runs
          git config --global --add safe.directory "$PWD"
          
          git fetch --tags --force

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: "Login to ghcr.io"
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push Docker images"
        run: |
            cd docker
            make GITHUB_ACTIONS=${GITHUB_ACTIONS} GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}

            docker image prune --force
            docker images

            make push GITHUB_ACTIONS=${GITHUB_ACTIONS} GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}
