name: Publish image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push image to multiple registries
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor || github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
            cd docker
            make GITHUB_ACTIONS=1 GITHUB_ACTOR=${{ github.actor || github.repository_owner }}

      - name: push images
        run: |
            docker images
            make push GITHUB_ACTIONS=1 GITHUB_ACTOR=${{ github.actor || github.repository_owner }}
